# Generated by Django 5.0.6 on 2024-08-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_host'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
